import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Previous from '../components/Previous'
import Upcomming from '../components/Upcomming'
import { client } from '../lib/client'

export default function Home({ bannerData, previousMatchesData, upcommingMatchData }) {

  return (
    <div className='overflow-x-hidden bg-gray-50'>
      <Head>
        <title>FC VIITORUL CORNU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <Banner banner={bannerData.length && bannerData[0]} />

      <div className="grid lg:w-9/12 gap mx-auto xl:grid-cols-3 lg:grid-cols-2 grid-cols-1">
        {previousMatchesData?.map((match) =>
          <div key={match._id} className="">
            <Previous match={match} />
          </div>
        )}
        <div className="order-first">
          <Upcomming match={upcommingMatchData[0]} className='' />
        </div>
      </div>


      {/* <Footer /> */}
    </div>
  )
}

export const getServerSideProps = async () => {

  const bannerQuery = '*[_type == "banner" ]'
  const bannerData = await client.fetch(bannerQuery)

  const previousMatchesQuery = '*[_type == "previous_matches" ]'
  const previousMatchesData = await client.fetch(previousMatchesQuery)

  const upcommingMatchQuery = '*[_type == "upcomming_match" ]'
  const upcommingMatchData = await client.fetch(upcommingMatchQuery)
  return {
    props: { bannerData, previousMatchesData, upcommingMatchData }
  }
}
